theme: jekyll-theme-minimal
title: Sistema de Gestão de Voluntários
description: Plataforma completa para gestão de voluntários e projetos sociais
show_downloads: true
google_analytics: # Adicione seu ID do Google Analytics se tiver